# Host for Apache and laravel 
#----------------------------------
php:
  image: cheezykins/laravel
  container_name: larapache
  links:
    - mysql
  ports:
    - "8081:80"
  volumes:
    - .:/var/www/html

# MySQL Container #----------------------------------------
mysql:
  image: library/mysql:latest
  container_name: larapache-mysql
  ports:
    - "10006:3306"
  expose:
    - "3306"
  volumes:
    - ./docker/data/mysql:/var/lib/mysql
    - ./docker/logs/mysql:/var/log/mysql
    - ./docker/config/mysql/unicode.cnf:/etc/mysql/conf.d/z_my.cnf
  env_file:
    - ./docker/mysql.env
